repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
        exclude: ^frontend/src/client/.*
      - id: trailing-whitespace
        exclude: ^frontend/src/client/.*
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 21.5b2
    hooks:
      - id: black
        language_version: python3.8

  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        language_version: python3.8
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, flake8-comprehensions]
        args: ["--max-line-length=88"]
        language_version: python3.8

  - repo: https://github.com/python/mypy
    rev: v0.812
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
        language_version: python3.8

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args: ["--configfile", "bandit.yaml"]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.28.0
    hooks:
      - id: eslint
        additional_dependencies: [eslint@7.28.0]
        files: \.(js|jsx|ts|tsx)$
        types: [file]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args: ["--profile", "black"]
